### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [Microsoft/Pyjion#139]
I would like to point out that identifiers like "[`__CEE_H__`](https://github.com/Microsoft/Pyjion/blob/1eb5dae71d9f208d63e9fb7f2432edff058444d8/Pyjion/cee.h#L26)" and "[`__PYJIT_H__`](https://github.com/Microsoft/Pyjion/blob/49564acfa9d5da867c614269386b2a6f16e1452d/Pyjion/pyjit.h#L26)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by brettcannon** [comment]
Thanks for pointing this out. Obviously not high priority, but we should fix this at some point.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoid undefined behaviour?")?

**Comment by brettcannon** [comment]
Since we are only targeting Visual Studio at the moment then we only need to currently worry about how that compilers treats this situation. If you want to submit a pull request I will happily review it, but right now I'm focusing on Python compatibility with Python so we can hopefully present this work at PyCon for inclusion in Python 3.6.
