### ISSUE TITLE
Unpause Development

### ISSUE THREAD

**Issue by shrmrf** [Microsoft/Pyjion#206]
Hello Everybody,

According to [the notice](https://github.com/Microsoft/Pyjion#a-note-on-development) in the readme, development is paused and waiting for python3.6 to come out. 

Now that python3.6 is out, and we're coming back to work, how about unfreezing the development? Although I'm not a contributor to Pyjion, but I'm really excited by the possibility to JIT-compile python. Also, if someone can point-out links (preferably inside [the README](https://github.com/Microsoft/Pyjion)) on how to write code for JIT optimization... it'd be great!!

A possibly related note: does it help to have static type checks e.g. with [mypy](https://github.com/python/mypy) enabled in code (can't we have Typescript for Python?? 🥇 )? Any comments are welcome... 

Thanks again for the awesomeness!

**Comment by brettcannon** [comment]
I've added a note about the infrequency of development in 488d7498f14667c34af291deca87cff6f9cb2507. Basically development is still infrequent based on when we have time, but we can at least start making progress again.

As for writing code for JIT optimization, just write Python code. 😉

And type annotations currently do not help because they cannot be trusted implicitly. We have considered making it an opt-in thing but not done anything beyond that.
